### ISSUE TITLE
Installation instructions for Ubuntu need additional line

### ISSUE THREAD

**Issue by zlite** [mavlink/qgroundcontrol#10306]
If you're installing QGC with Ubuntu 20.x under WSL, you need one more line in the installation instructions:

sudo apt-get install -y libpulse-dev

**Comment by Arccoma** [comment]
> If you're installing QGC with Ubuntu 20.x under WSL, you need one more line in the installation instructions:
> 
> sudo apt-get install -y libpulse-dev

![f83593fe-fc12-4b95-9c60-1b54df82ccc6](https://user-images.githubusercontent.com/102889296/179901412-de011bb0-6652-4078-8ce3-2a7c7fce0b27.png)

in my case(https://github.com/mavlink/qgroundcontrol/issues/10350), the map is broken.

**Comment by droneOTTO** [comment]
what about Ubuntu 22.04?

I cant launch QGC, i keep getting qt.network.ssl: QSslSocket: cannot call unresolved function error.

please explicit explanation, I am new to linux and installing things.

**Comment by DieBorr** [comment]
Hi @droneOTTO , I also had that problem some time ago, the problem was resolved at least for me when I changed to ubuntu 20.xx , If u need some explanation after some research I found that OpenSSL was one of the main problems, Actually I'm not very familiarized with OpenSSL but there is a problem with that, hope this can help you if you haven't found the problem.

**Comment by enriquesbr** [comment]
I have similar issue  like yours my current version is openssl/jammy-updates,now 3.0.2-0ubuntu1.13 amd64 [installed] by any change do you know which version is required by Qgroundcostrol ?
