### ISSUE TITLE
Feature Request: Custom Example made available for download (ready to use)

### ISSUE THREAD

**Issue by kschoelpple** [mavlink/qgroundcontrol#10794]
Background: In Android (5.5" landscape used as an example) the instrument panel is rather large in proportion to the rest. As such it is blocking a lot of background video / map.  
Also the recording button is excessively large at that screen size.
![Original on 5 5](https://github.com/mavlink/qgroundcontrol/assets/32047349/bda7a988-b929-4e35-be80-cc9587bfe1a5)

This would solve various issues and provide every user with a choice between standard version and the custom example.
![Modified QGC](https://github.com/mavlink/qgroundcontrol/assets/32047349/ed82ae3f-6cef-40c8-8548-e68ca52a1ab5)

Also been trying to build from source, but due to lack of experience and problem with "Android missing platform tools" which no one appears to have an answer for.

**Comment by HTRamsey** [comment]
The instrument panel has been rewritten in master and might be usable on a device that small now, otherwise you can disable from settings. The Android missing platform tools likely has to do with the Android SDK installation, which can easily be managed in QtCreator. The custom build stuff is currently being rewritten in master, and may be a bit easier to set up soon. Feel free to reopen if you have any other questions.
