### ISSUE TITLE
Custom build doesn't work on master branch

### ISSUE THREAD

**Issue by danieffe** [mavlink/qgroundcontrol#10840]
When I try to build the custom-example build it gives me some errors (Ubuntu 22.04, I'm building using the comunity docker container):
![Schermata del 2023-10-25 15-52-50](https://github.com/mavlink/qgroundcontrol/assets/120368602/5003acdd-7f09-4675-a2aa-73b76d119b47)
![Schermata del 2023-10-25 15-53-06](https://github.com/mavlink/qgroundcontrol/assets/120368602/85969267-000b-43d1-bcdc-fd69edf069ce)
[](url)

I did all the steps in the README: Rename folder from custom-example to custom, run in it updateqrc.py and compile but it doesn't work.

**Comment by JMare** [comment]
I tried the build and had the same issue. The problem is because the normal builds now use the mavlink dialect 'all' while the custom build overrides this and uses 'common' which doesnt have the new development messages.
This changed from #10783

You can fix this for now by changing MAVLINK_CONF = common to MAVLINK_CONF = all in custom.pri

There seems to be a bit of discussion about whether using the 'all' dialect for the normal builds is a good idea in #10836, so for now maybe just make the change locally.
