### ISSUE TITLE
Restore iOS Builds

### ISSUE THREAD

**Issue by HTRamsey** [mavlink/qgroundcontrol#11295]
Doesn't seem like too big of an issue to get these back up, but I don't personally have a way to test it.

**Comment by HTRamsey** [comment]
@DonLakeFlyer What are your thoughts on this? Is this something anybody has been asking for?

**Comment by DonLakeFlyer** [comment]
The problem is you can build something. But there is no realistic way to get it onto an iPhone the way the phone is locked down. Someone would need to setup up their own beta dev program in apple play. And then I think you can get an app onto a phone which didn't come through the store. But you need to put the phone on a dev mode as well if I remember. All of which is nothing a normal user will ever do. You can't just stuff things onto an iPhone like you can with Android.

The only useful case would be if an iOs build went directly from CI to Apple Play. There used to be a guy who would hand carry stable releases to the store and release them. He's gone now and I never bother with trying to do it manually. There hasn't been an iOs store update of QGC in 5-6 years.

**Comment by DonLakeFlyer** [comment]
As far as commercial folks. I only know of Sentera that had an iOS custom build they released. But they did that ll on their own.

**Comment by HTRamsey** [comment]
Isn't that changing as of ios17? I think the EU is pushing them to allow sideloading apps.

**Comment by HTRamsey** [comment]
Taken from Reddit:

"The point is that installing 3rd party apps, so called 'sideloading', currently has a few restrictions, such as requiring a developer account (free or paid) and the installed apps being effectively linked to your account.

Additionally you have to reinstall once a week (free) or year (paid), the apps are not permanently installed.

With the new EU regulations, all those downsides are supposed to disappear and 'sharing apps' should theoretically be as easy as simply sending someone an IPA-file, which the other guy then can freely install on-device.

IOS 17.0.x currently does not contain any changes in regards how 3rd party app installation works, but since those new regulations become mandatory as of March 2024, it is expected to be included in a future update (likely 17.2 or 17.3)."

So maybe it's not important unless people ask for it, but if we can at least provide a working CI workflow that builds it, it might be worth mentioning in the docs.

**Comment by DonLakeFlyer** [comment]
Ah, interesting. Certainly can't hurt to have CI iOS then.

**Comment by HTRamsey** [comment]
Closing since we have a usable CI workflow now.
