### ISSUE TITLE
Restructure Vehicle to Not be a Fact Group

### ISSUE THREAD

**Issue by HTRamsey** [mavlink/qgroundcontrol#11428]
Kinda seems odd the vehicle class itself inherits a fact group. Move those facts into their own fact groups.

**Comment by DonLakeFlyer** [comment]
I think that would add an additional level of hierarchy to the object model when referenced from script. vehicle.foo would become vehicle.bar.foo. Which will in turn break folks who have customized the telemetry display. If I remember correctly that stores property names with the full object hierarchy in settings. I'm not 100% sure of that since I haven't been in there in a while.

**Comment by DonLakeFlyer** [comment]
That's right I forgot all those properties were defined in there anyway.
