### ISSUE TITLE
What GStreamer version to use when building the latest master?

### ISSUE THREAD

**Issue by funyarinpa01** [mavlink/qgroundcontrol#11863]
Building 49424a35c5337391e41c1cd1e7bbd4b7ee7bc330 with qmake against GStreamer 1.18 as described in the readme worked fine on Ubuntu 22.04 arm64, Windows 10 x86_64, Apple M1, but after my latest rebase (9aa0f051ff77748e3c407ab1fb2e840705956be4) I had to update GStreamer on Windows at least to 1.20+ to build with cmake. While macOS looks up for gstqt6elements.h in src/VideoManager/VideoReceiver/GStreamer/qmlglsink/qt6 which looks like

```c++
#include <gst/gst.h>

G_BEGIN_DECLS

void qt6_element_init (GstPlugin * plugin);

// TODO(zdanek) fix after switching to gstreamer 1.20.0+
// original code from 1.20.0
// GST_ELEMENT_REGISTER_DECLARE (qml6glsink);
// backported to:
extern "C" { gboolean gst_element_register_qml6glsink (GstPlugin * plugin); };

G_END_DECLS
```

On Windows it's build/Desktop_Qt_6_6_3_MSV2019_64bit-Debug/_deps/gstreamer_good_plugins-src/ext/qt6, for example

```c++
#include <gst/gst.h>

G_BEGIN_DECLS

void qt6_element_init (GstPlugin * plugin);
 
GST_ELEMENT_REGISTER_DECLARE (qml6glsink);

G_END_DECLS
```

The question is which GStreamer version should be ultimately used and where is the recipe which creates the Windows folder so the dependency version can be managed

**Comment by HTRamsey** [comment]
Oh I finally figured out the issue it will be fixed in #11806. That PR is taking a bit because I want every build system to work 100%. Turns out you can't let Linuxdeploy include any gstreamer libraries in the appimage or you get mismatched version issues. The other option is to build gstreamer 100% statically, which is available as of 1.24, and I was experimenting with that too. GStreamer sucks to work with tbh
