### ISSUE TITLE
parameters and flight modes view distorted

### ISSUE THREAD

**Issue by thomasgubler** [mavlink/qgroundcontrol#1328]
![screenshot from 2015-03-06 20 36 01](https://cloud.githubusercontent.com/assets/1419479/6534775/71dc90f4-c440-11e4-982c-26d5f2f87309.png)

The bar on the left moves towards the center and the parameter widget is tiny and strangely placed.

Here is the Summary screen for comparison.
![screenshot from 2015-03-06 20 37 28](https://cloud.githubusercontent.com/assets/1419479/6534804/9f00dc2a-c440-11e4-9e5f-a36b30d3405e.png)

This is with QT 5.4.1,

**Comment by thomasgubler** [comment]
Same for flight modes:
![screenshot from 2015-03-06 20 42 38](https://cloud.githubusercontent.com/assets/1419479/6534935/65c6278e-c441-11e4-9a68-a0876124f537.png)

**Comment by LorenzMeier** [comment]
I have the same effect on a laptop screen.

**Comment by dogmaphobic** [comment]
I just assumed it to be WIP...

**Comment by DonLakeFlyer** [comment]
Yup. Non-qml setup screens are a bit out of whack right now with respect to positioning. I had been leaving them only since I was converting them over one at a time. With Flight Modes to Qml now it's just parameters left. So it's easy enough to fix just that one. Conversion of that screen to Qml is not high pro.

**Comment by DonLakeFlyer** [comment]
Fixed. New Flight Mode fixes Flight Mode.
