### ISSUE TITLE
Parameter loader doesn't always complete load

### ISSUE THREAD

**Issue by DonLakeFlyer** [mavlink/qgroundcontrol#1436]
When running over Radio you've got a 10-15% chance that the parameter load doesn't finish. It sits at the end waiting for 1 or more params to come down. Not sure why yet. Maybe missing one on the wire and then the re-request logic isn't working correctly.

**Comment by severinleuenberger** [comment]
I recognize this behaviour as well, and I download every few days the new qgroundcontrol beta version with your newest fixes. Its still there now. 
After disconnecting and connecting (sometimes 2 times neccessary) it loads correct again. 
But it seems to be a real bug, because I see this at least every 4th restart.

**Comment by DonLakeFlyer** [comment]
Are you running latest firmware master? There was a bug in firmware which was causing this.

**Comment by severinleuenberger** [comment]
ok, I will just test with another board who has the newest px4 firmware.

**Comment by DonLakeFlyer** [comment]
Forget I had entered this issue! Using both latest firmware master and QGC Daily this is fixed.

**Comment by severinleuenberger** [comment]
Ok, indeed, I just testet with latest firmware and QGC Daily, and everything is fine again!
