### ISSUE TITLE
panic shutdown on connecting to PX4Flow

### ISSUE THREAD

**Issue by kd0aij** [mavlink/qgroundcontrol#1508]
complains there is no SYS_AUTOSTART parameter and segfaults

**Comment by DonLakeFlyer** [comment]
What do you means connecting to PX4Flow? You are connecting QGC to a PX4Flow directly? If so, to do what?

**Comment by kd0aij** [comment]
That's how I used to focus the camera

**Comment by kd0aij** [comment]
https://pixhawk.org/modules/px4flow#image_quality_and_output

**Comment by DonLakeFlyer** [comment]
Ok. Thanks. I'll have to look but it seems like the PX4Flow is incorrectly reporting itself as a Pixhawk with the px4fmu stack running on it.

@LorenzMeier I haven't debugged but it looks like the flow board is incorrectly reporting itself as a MAV_AUTOPILOT_PX4 in the heartbeat message. This causes the autopilot plugin system to think it's a Pixhawk running px4fmu stack. I've never delved into the flow source. If you have, maybe quick check to see what's going on here. It needs to report itself as MAV_AUTOPILOT_GENERIC since their doesn't seem to be a MAV_AUTOPILOT entry for flow.

**Comment by DonLakeFlyer** [comment]
Lorenz is fixing this

**Comment by LorenzMeier** [comment]
Fixed.
