### ISSUE TITLE
alert-text instead of a symbol with exclamation mark

### ISSUE THREAD

**Issue by severinleuenberger** [mavlink/qgroundcontrol#1586]
I would prefer to see directly the mavlink error message instead of a red flag with exclamation mark and number of messages. 
On rollover, the function it can be as it is now. 
Default view should be: alwasys the last message. 
Something like this: 
![image](https://cloud.githubusercontent.com/assets/9945167/7696025/ac07ffe2-fdf8-11e4-942a-99a68040ffde.png)

**Comment by LorenzMeier** [comment]
I don't think this will scale or be particularly readable. If we want to show them more prominently then we would need to do them as banner below the status bar or something similar.

**Comment by LorenzMeier** [comment]
@dogmaphobic @DonLakeFlyer Most users miss the messages in the toolbar because a lot of icons are red there essentially just indicating "normal" things like no GPS lock. It would make sense to show a banner over the top of the current active Widget (so its still readable) with those messages for a few seconds.
Its a recurring pattern, and its extremely relevant for the overall user experience.

**Comment by DonLakeFlyer** [comment]
Yesterday I flew with Tower on my Iris with the APM stack. It was pretty interesting. This whole QGC top bar thing needs to be reworked to be more user friendly and useful while flying. I've took a lot of notes for things to change.

**Comment by LorenzMeier** [comment]
Implemented!
