### ISSUE TITLE
Param descriptions not in QGC

### ISSUE THREAD

**Issue by mswingtra** [mavlink/qgroundcontrol#1758]
Hi guys,
How can I forward parameter descriptions (group, units, min/max etc.) to QGC? The xml file is generated correctly and all the right comments are made, but still in QGC only default params are shown. 
Cheers

**Comment by DonLakeFlyer** [comment]
Are you missing parameters entirely or are you missing updated meta data for parameters? If you are missing meta data:
- Flash your modified firmware to the board using QGC. You must select the .px4 file if you are flashing a custom file.
- Reboot QGC
- They should be there now.

Also if you want to just ask questions, please post to the mailing list first instead of entering an issue.
