### ISSUE TITLE
Edit view should show vehicle icon

### ISSUE THREAD

**Issue by LorenzMeier** [mavlink/qgroundcontrol#2103]
I'm still very confused by not seeing my vehicle while I'm editing waypoints. The home position is not enough since I tend to carry it around to work out where to put my waypoints exactly. There doesn't seem to be any harm in having the vehicle present.

**Comment by DonLakeFlyer** [comment]
Unforunately this is not as easy as it looks. Reason it that once you have the vehicle on the map you are going to want to add a waypoint at the vehicle position and you won't be able to do it because you can't click through the vehicle which is above the map click handler for adding waypoints. Have to think about it some.

**Comment by LorenzMeier** [comment]
Closing as stale.
