### ISSUE TITLE
Font issue with daily build under windows

### ISSUE THREAD

**Issue by sirPerna** [mavlink/qgroundcontrol#2264]
I just tested the daily QGC build under windows 10 64bit. It looks like ther is an issue showing the text correctly.

**Comment by sirPerna** [comment]
Here is a picture how it looks like.
![font issue](https://cloud.githubusercontent.com/assets/7645907/11333802/b72df37e-91d0-11e5-9428-5d0e417a8f0a.png)

**Comment by DonLakeFlyer** [comment]
Is it all fonts size in all location? Or just a specific size or location?

**Comment by sirPerna** [comment]
Looks like specific size and location
![2015-11-23_200835](https://cloud.githubusercontent.com/assets/7645907/11346663/02ec138e-921e-11e5-96ae-af2bca8a2d5b.png)
I see it on all selected drop downs but when you click on the drop down the other entries are fine. I also see it on the text for the firmware update and where you select the firmware you want to load. Also on all text boxes but only the text inside the text box.

**Comment by LorenzMeier** [comment]
@sirPerna Can you re-try the current daily? There was a recent switch in some of the infrastructure code which might have improved things. Quite possible that we fully need to switch to QML on desktop as well to completely fix it though.

**Comment by DonLakeFlyer** [comment]
This is some strange thing in Qt. I can report it, but I can't figure out what is going on. It only happen in Combo Boxes in this panel. They are fine other places in the code.

**Comment by sirPerna** [comment]
@LorenzMeier Just tested but the issue is still there (v2.8.0-202-g9f86fc0)

**Comment by DonLakeFlyer** [comment]
This is a Qt bug. Given the fact that I'm going to re-work this screen post 3.0 release it not worth try to hack around some more to work around the bug. At this point a work around doesn't seem possible. Moving out of the 3.0 release.

**Comment by NaterGator** [comment]
This bug is related to the [renderType](http://doc.qt.io/qt-5/qml-qtquick-text.html#renderType-prop) being set to NativeRendering when there are some transformations applied or inherited. 

For example, to fix the Firmware page simply add `renderType: Text.QtRendering` [here](https://github.com/mavlink/qgroundcontrol/blob/0d962e0a66ba6c421362edc2f42b0ef128b3de6a/src/VehicleSetup/FirmwareUpgrade.qml#L378).

I'm unclear on when this default changed / how certain QML components are inheriting NativeRendering, but that's the issue (it is very briefly touched upon [in the docs](http://doc.qt.io/qt-5/qml-qtquick-text.html#renderType-prop)).

**Comment by NaterGator** [comment]
Per [this](https://bugreports.qt.io/browse/QTBUG-46030) Qt bug report the issue can also be mitigated by not using fractional positioning of the SetupView.

**Comment by DonLakeFlyer** [comment]
@NaterGator Thanks for the fix on this.
