### ISSUE TITLE
Waypoint operation does not work

### ISSUE THREAD

**Issue by Fojtik** [mavlink/qgroundcontrol#2288]
Waypoint operation does not work, see attached image. The planner display track correctly, but the flight map is not correct. May be that you are using very aggresive rounding.
![waypointmerging](https://cloud.githubusercontent.com/assets/2893993/11423626/49051364-9446-11e5-9849-cac4da950480.jpg)
![waypointplanner](https://cloud.githubusercontent.com/assets/2893993/11423653/8a564504-9446-11e5-8ac2-5e4a24d1078a.jpg)
You have made a very big step backward with a new mission editor. All of this already worked.

**Comment by LorenzMeier** [comment]
@DonLakeFlyer You have to ensure that you are *only* ever rounding during visualisation. You need to make sure to save / print those numbers with at least 18 digits of precision.

**Comment by DonLakeFlyer** [comment]
@Fojtik Can you attach the waypoint file? Also specify the exact set of steps your used to repro this.

@LorenzMeier I'm using 7 digit rounding for display values in the ui and 18 digit file format output precision. I believe this is exactly the same as the old code.

**Comment by DonLakeFlyer** [comment]
@Fojtik Also where are you getting this build from? Are you building yourself? Or are you using a daily. If daily, which one The visuals still look like they are coming from an older build.

**Comment by Fojtik** [comment]
Before 2 years I can build QGC. Now it is not possible for me to build it.
Waypoint file is a same - AroundCech.waypoint we already discussed.

I have loaded this file and uploaded to my emulator. These two screans appeared.

I can explain more details on Email.

**Comment by DonLakeFlyer** [comment]
Use the gitter channel https://gitter.im/mavlink/qgroundcontrol for discussion on build problems.

**Comment by DonLakeFlyer** [comment]
This is a bug in master. Stable works, although it doesn't allow you to edit. Which is correct behavior in Stable, since this set of waypoints is using settings which are not supported by visual editing.

The bug is that the values are incorrectly getting coverted back and forth to an int when sent to a vehicle. Introduced by the new raw edit capability just added and a bad copy constructor which wasn't setting the FactMetaData correctly. Unit test didn't catch it because the test values I was using don't have any digits past the decimal point. Fixing that all up now.

**Comment by DonLakeFlyer** [comment]
This still leaves the issue that you are using a MAV_CMD=0 which from a mavlink standard standpoint is not really supported. I'd rather not implement a mechanism to support editing of unknown MAV_CMD ids. My suggestion would be to add a couple MAV_CMD_USER1, MAV_CMD_USER2 ids to the mavink spec that can be used by anyone to code custom commands. Then that could be supported in a standard way. Other option is to just take over one of the other real MAV_CMD ids and use that instead of 0.

**Comment by LorenzMeier** [comment]
Yes. Lets reserve a range of 20 commands. But it should not be USER1 but suggesting it should never ever be used in a production system, like TESTING1 or DEBUG1. While at it we should establish a range reservation for these. we have an int16 here, so plenty of ranges to reserve.

**Comment by DonLakeFlyer** [comment]
I'll put together a mavlink pull for it. Thanks Lorenz.

**Comment by Fojtik** [comment]
I can pack "my" waypoint to any MAV_CMD that you recommend. This was only a first attempt to do something.

**Comment by DonLakeFlyer** [comment]
Ok. Until I get around to adding the new MAV_TESTING MAV_CMDs tp mavlink and update QGC yo can just pick one of the existing MAV_CMDs to take over for your use. I'd suggest something that doesn't have already have a friendly editor associated with it like say MAV_CMD_DO_SET_PARAMETER. Then you can try this whole thing again using the latest daily build to see if you are still having problems. Let us know how it goes.

**Comment by DonLakeFlyer** [comment]
This should bd working now, so closing. Will re-open if there are still problems.

**Comment by Fojtik** [comment]
Yes, you are right, current daily snapshot does not suffer with reported issue.

**Comment by DonLakeFlyer** [comment]
Great, thanks for reporting back @Fojtik
