### ISSUE TITLE
manual control lost and regained

### ISSUE THREAD

**Issue by ChristophTobler** [mavlink/qgroundcontrol#2293]
when I run a simulation with gazebo and use the default UDP link in qgc, I get "MANUAL CONTROL LOST" and "MANUAL CONTROL REGAINED" all the time. see sceenshot (I use a Logitech joystick and it works from time to time)
![qgc_manual_control_lost](https://cloud.githubusercontent.com/assets/14769636/11443093/7aec5e12-951a-11e5-8107-202ae1385d99.png)

**Comment by DonLakeFlyer** [comment]
I"m going to have to debug this through from the QGC to the Firmware side. It seems like the time delta for lost control is way too large. Worried that UDP pipe is delayed somehow.

**Comment by DonLakeFlyer** [comment]
@LorenzMeier I instrumented both QGC and Firmware SITL (I used the driver_framework branch) side to output message times. Then tested on mac SITL. QGC is correctly sending MANUAL_CONTROL at about 25hz, whereas Firmware side if only seeing anout 4Hz of MANUAL_CONTROL commands. Do you think you could help out here? Not sure if firmware is tossing some MANUAL_CONTROL messages because it's busy or maybe it's losing UDP packets. Not really sure.

**Comment by ChristophTobler** [comment]
@DonLakeFlyer I guess: "Do you think you could help out here?" was also meant for @LorenzMeier.? (not sure because he is not a participant) Or can I help or provide more info?

**Comment by DonLakeFlyer** [comment]
Yes, hoping that @LorenzMeier can help to debug from the firmware side of things.

**Comment by tumbili** [comment]
We know now what the problem is. Me and @ChristophTobler were working on the same network and so our QGC's would connect to the other one's SITL.

**Comment by ChristophTobler** [comment]
True. That was one problem. But the MANUAL_CONTROL lost still exists most of the time which has to do with the lidar/opticalflow messages, I guess.

**Comment by ChristophTobler** [comment]
Was publishing on UDP Port 14550 instead of 14556. Problem disappeared. Thanks!
