### ISSUE TITLE
Configurable units in the instruments / flight view

### ISSUE THREAD

**Issue by julianoes** [mavlink/qgroundcontrol#2574]
It would be nice if the units of the flight view could be changed, for instance I'd want to use m/s instead of km/h.

If this has already been added after 2.8.0, excuse my ignorance!

**Comment by DonLakeFlyer** [comment]
This is doable but first the firmware needs to standardize on parameter unit definitions. Right now most parameter units are just unknown quality strings. So you can't really trust that "km/h" is what you expect in order to translate it. It requires validation of units on the firmware parameter meta data generation side as well as validation against a known set.

**Comment by julianoes** [comment]
Ok but the units are mostly defined in the mavlink comments, right?

**Comment by DonLakeFlyer** [comment]
Ah, sorry you said "Flight View". Those are more locked down and don't need parameter meta data. That could all be done on the QGC side.

**Comment by julianoes** [comment]
Yes, I guess that's what I meant.

**Comment by julianoes** [comment]
FYI @georgehines

**Comment by DonLakeFlyer** [comment]
Need to consider whether for now we change to m/s and do confgurability in 3.1

**Comment by DonLakeFlyer** [comment]
@lorenz Feedback?

**Comment by dagar** [comment]
Despite my best efforts airspeed in knots and height in feet is going to be important for us.

**Comment by DonLakeFlyer** [comment]
This is easier to do now that instrument panel is using the FactGroup stuff.
