### ISSUE TITLE
Font issue - QGC + Windows

### ISSUE THREAD

**Issue by marimach77** [mavlink/qgroundcontrol#2993]
@DonLakeFlyer Not sure if others also have the same problem. I'm using always QGC daily builds installed on Windows 7 x64. Flight Modes setup screen seems to have a font issue. Fields are too short and no PWM bands. Same issue on my other 3 computers.

![qgc_font_issue_windows_7](https://cloud.githubusercontent.com/assets/8745910/13710350/4d0e5ca6-e7b9-11e5-9389-fc35140bd9c5.PNG)

**Comment by DonLakeFlyer** [comment]
@LorenzMeier I can make these combo boxes a bit wider. But the meta data for these params needs to be cleaned up. No "ALL CAPS". And the "Rc Channel ##" seems a bit noisy as well. Why not just "Channel ##", or even just "##"?  It's worthwhile considering shortening as much as possible. Would "Altitude Ctl" or "Alt Control" work. Reason is that if I need to expand everything for such long wording it wreaks havoc on small screens. The other issue is that the naming in this meta data needs to match the naming and capitlization in the QGC flight modes dropdown. Otherwise users get confused. There is another issue on that somewhere.

**Comment by DonLakeFlyer** [comment]
I'll adjust once the final decision on what the names of these are comes through.

**Comment by DonLakeFlyer** [comment]
I'll move the meta data issue to a PX4 Issue

**Comment by DonLakeFlyer** [comment]
@marimach77 Thanks for the bug report. Keep 'em coming!
