### ISSUE TITLE
Allow more zoom on the map

### ISSUE THREAD

**Issue by julianoes** [mavlink/qgroundcontrol#3111]
I think it would be better if the map could be zoomed closer, even if it involves scaling the available map tiles. The use case for me is to set a multicopter mission with waypoints close to each other.

As far as I remember, in previous versions it was possible to zoom in closer.

**Comment by julianoes** [comment]
Is this hard to do? Could you give me pointers where I would have to dig? Thanks.

**Comment by DonLakeFlyer** [comment]
I would assume it's quite involved. I means the map code needs to generate tiles on the fly (by blowing up lower zoom tiles) for the higher zoom levels which it doesn't have data for.

@dogmaphobic Would know more.

**Comment by julianoes** [comment]
Ok, I understand, thanks.

**Comment by booo** [comment]
Can you use a external tile server and a custom map url? As far as I can see there is an option for custom tile servers in QGC. Maybe it needs some documentation.

**Comment by DonLakeFlyer** [comment]
This is "sort of" supported now. It will allow you to zoom up past the level where there are tiles and it blows up the existing tiles. I say "sort of" because you need to start lower than where tiles exist and then zoom up from there. If you start directly at the high zoom level it won't work. Better than nothing and likely as good as it's going to get.
