### ISSUE TITLE
The distance about planned home position is minus

### ISSUE THREAD

**Issue by glody** [mavlink/qgroundcontrol#3682]
Test Environment
QGroundControl: Daily Build: v2.9.7b-335-g4f119b3
Windows: Windows 8.1 64 Bit Laptop
Linux: Ubuntu 14.04 64 Bit Laptop
OS X: OS X 10.11.2 MacBook Pro
Android: Android 5.1.1 Nexus 9 Tablet
Purpose:
Check if the tips about planned home position is correct
Step:
1. Lanuch QGC
2. Check the distance tips on mission page
Excepted result:
The distance about home position should be 0M
Actual result:
The distance is -1M, it doesn't make sense

![distance-1m](https://cloud.githubusercontent.com/assets/1768868/16404430/82b9ed02-3d31-11e6-9397-7c83c428bf4f.JPG)

**Comment by DonLakeFlyer** [comment]
@glody Can you make sure you are doing your testing on the latest daily build instead of Stable. Stable is very old now. So this is different now. It actually exposes a different bug!

<img width="1015" alt="screen shot 2016-06-28 at 7 36 30 pm" src="https://cloud.githubusercontent.com/assets/5876851/16438829/a360e00c-3d67-11e6-9ccc-996be20c9191.png">

**Comment by glody** [comment]
@DonLakeFlyer Yes, I am using daily build for our testing. I found this issue on daily build 24/06/2016.

Re-check on daily build 01/07/2016, this issue still able to reproduce. the build version is v2.9.7b-379-g2e9d112.

Reprodue steps:
1. Set some waypoints
2. Select home point
3. Check "distance" shows in tips


![distance-1m_02](https://cloud.githubusercontent.com/assets/1768868/16556306/dfd0a128-420b-11e6-85bb-075ec21b1365.JPG)

**Comment by DonLakeFlyer** [comment]
This is fixed now. For real!
