### ISSUE TITLE
Choose a reasonable precision for presenting very small param values in the UI

### ISSUE THREAD

**Issue by hsteinhaus** [mavlink/qgroundcontrol#3975]
When setting up ArduCopter, I usually have to work with very small ATC_RATE_*_D values. 0.0005 is an absolutely reasonable value for certain ESC/motor/prop/battery combinations. D=0.001 is producing heavy D oscillations, while with D=0.00001 the oscillation is in the P term. Unfortunately, QGC is displaying 0.0005 as 0.001, while 0.00049 is displayed as 0.000.

**Comment by DonLakeFlyer** [comment]
I need to look to see where the precision is coming from for those param. Possibly an issue with auto-generation of decimal places from increment.

**Comment by DonLakeFlyer** [comment]
@hsteinhaus I can't seem to find the parameters you are talking about: http://ardupilot.org/copter/docs/parameters.html? Only thing that starts with ATC_RATE is ATC_RATE_FF_ENAB?

**Comment by hsteinhaus** [comment]
The correct name is ATC_RAT_RLL_D. However, I think the most params ending on "_D" could be affected in the same way (ATC_RAT_RLL_D, ACCEL_Z_D, ATC_RAT_YAW_D, AUTOTUNE_MIN_D).

**Comment by DonLakeFlyer** [comment]
Thanks @hsteinhaus I'll check to see what parameter meta-data is set on those for decimal precision.

**Comment by DonLakeFlyer** [comment]
This is due to the increment meta data possibly being set too high. Need to talk with ArduPilot folks about meta data change or add decimalPlaces meta data.

**Comment by DonLakeFlyer** [comment]
@rmackay9 Any comments on this. Current state:
* ArduPilot param meta data does not yet support specification of decimal places for editing. QGC does support such a thing.
* When decimal places is not specifies QGC falls back to using Increment meta data as the indicator for decimal places.
* For the example ATC_RAT_RLL_D above Increment is specified as .001 which in turn cause QGC to use 4 decimal places for editing (1 more thank increment).

Questions:
* Given the above comments is an increment of .001 a good setting for this param. Or should it be .0001?
* If .001 is a good increment but you really need more decimal places to edit then I think ArduPilot needs to add decimal place meta data. I can mod the parser, but someone will need to look at as a starting point the PID related params to set values decimal place settings. Would ArduPilot folks be interested in doing that? Using a known set of decimal places makes editing parameter much easier so you don't run into way long floats when shown as strings due to float inprecision..

**Comment by DonLakeFlyer** [comment]
Float params which end in _P, _I or _D default to 6 decimal places.
