### ISSUE TITLE
Plane: Need icons for Mission/GeoFence/Rally buttons

### ISSUE THREAD

**Issue by DonLakeFlyer** [mavlink/qgroundcontrol#4101]

**Comment by dogmaphobic** [comment]
I looked at it today and I think it would make more sense to make it into a tab control. If you miss click, and click somewhere in between the icons, you end up adding a waypoint (or action depending on the mode you are in).

So instead of this:
<img width="295" alt="screen shot 2016-10-26 at 10 35 48 pm" src="https://cloud.githubusercontent.com/assets/749243/19752942/f0415c92-9bce-11e6-854e-15c01f369aae.png">

Use some tab like control (this is made up in Photoshop, not a real control):
<img width="295" alt="tabs" src="https://cloud.githubusercontent.com/assets/749243/19752946/fa72ea8c-9bce-11e6-9b5e-a5052bce38ae.png">

**Comment by DonLakeFlyer** [comment]
Tab won't work because you can have multiple of the little yellow boxes under it now just one. I'm think I'm going to just switch these to radio buttons instead of using a icon. Much simpler.

**Comment by DonLakeFlyer** [comment]
Switched to Radio Buttons. No icons needed.
