### ISSUE TITLE
Hover Throttle Tuning Reversed

### ISSUE THREAD

**Issue by fhpage** [mavlink/qgroundcontrol#4309]
I appears that "Hover Throttle" Tuning is reversed for my configuration. Moving the slider to the left slows the motors down (with no stick movement).  The description indicates that the motors should increase in rpm by moving tuning slider to the left - 
This is for:
Quad Rotor
Pixhawk with PX4 1.4.4
Taranis with D4R- II 
QGC v3.0.2

**Comment by DonLakeFlyer** [comment]
Took a look at this. Text says:
_Adjust throttle so hover is at mid-throttle. Slide to the left if hover is lower than throttle center. Slide to the right if hover is higher than throttle center._

So if your vehicle is hovering with throttle lower than center stick then center stick is too much power to hover. Which means you need to reduce power, hence you need to slow the motors which is moving the slider to the left as the text says. 

Don't see the problem here. Looks correct to me.
