### ISSUE TITLE
where did vehicle type go ?

### ISSUE THREAD

**Issue by AndKe** [mavlink/qgroundcontrol#5109]
when planning (not connected), I would expect to choose between plane & VTOLs right here:
![screenshot from 2017-05-08 19-14-42](https://cloud.githubusercontent.com/assets/1468842/25816430/5f9513f2-3424-11e7-9188-b4baa64e998a.png)

before, the setting was in QGC configuration, now it's gone ?

**Comment by DonLakeFlyer** [comment]
Click on Vehicle Info

**Comment by AndKe** [comment]
By adding "survey" , the vehicle type and AP type is hidden (like the screenshot above). 
Please *disable* the vehicle type and AP type, instead of hiding it, it could even be useful when loading and inspecting a saved mission.

**Comment by DonLakeFlyer** [comment]
Vehicle Info goes away as soon as you add a mission item. This is by design. A mission and the mission items themselves are targetted to firmware/vehicle type. This is because the behavior of the mission items values as well as what fields are actually available are specific to a firmware/vehicle combination. As soon as you add an item to the mission you have locked down the full set to the firmware/vehicle type.

**Comment by AndKe** [comment]
Yes, I know it's by design, but if the design were to disable the droplists, and still let them be visible, there would not be any confusion. 
Also, should you load a mission a year later, or receive from somebody else, you would instantly know what it is made for.
So please consider not hiding, but instead disabling them from being changed.

**Comment by DonLakeFlyer** [comment]
Ah ok, I see. I changed that somewhere along the way which was wrong.
