### ISSUE TITLE
USB; in case of error, try next port

### ISSUE THREAD

**Issue by AndKe** [mavlink/qgroundcontrol#5148]
ttyUSB0 was a leftover of an unplugged device.  (I've seen this happen sometimes on the USB3.0 ports, likely due to  a bad USB root hub.)
anyway, ttyUSB1 and 2 were there , and were fine.

I kept getting this message over and over again, (every ~3-5 seconds) I am not even sure if they would go away is mavlink was detected on one of the other ports, or if the others were checked at all, but this notification could be handled better. 

![screenshot from 2017-05-13 19-38-59](https://cloud.githubusercontent.com/assets/1468842/26033041/b8a1281e-38a2-11e7-84f4-54c73b699d38.png)

**Comment by DonLakeFlyer** [comment]
QGC thinks there is something it can auto-connect to plugged in to ttyUSB0, hence it tries to auto-connect to that port which then fails since it is in some strange zombie state. Not much QGC can do here since from it's point of view it doing the right thing. Could try to do some fancy, don't try to connect to a port which failed recently. But that would lead to additional complexity which could just make things for buggy for the normal case. Given this is a strange case I"m going to leave things alone.
