### ISSUE TITLE
KML/SHP/POLY import support for polygons

### ISSUE THREAD

**Issue by AluBis** [mavlink/qgroundcontrol#5752]
Hi,
I am new on this so not sure if this is the right place for my question.
But: I am looking for to import a polygon (.shp, .kml, .poly,...) to create a survey plan with a zone corresponding to precise coordinate. 
Mission Planner do this and it is really necessary for my activity: I realize photogrammetry for archeology, so there is no "mark", no building in satellite view to help me and I can't fly on a approximative zone.
There is any way to do it ?

**Comment by DonLakeFlyer** [comment]
Not yet supported. But coming in the 3.3 release.

**Comment by AluBis** [comment]
OK, it's a good news thanks ! But I don't understand why it is so difficult to find this features in almost all software.

**Comment by Antiheavy** [comment]
+1 for this feature request.

**Comment by kikislater** [comment]
+1 also

**Comment by RobDeBagel** [comment]
+1 for this also. I don't know the codebase or your plans that well but I'd suggest GDAL/OGR for import/export duties as it abstracts away this problem for pretty much every raster/vector GIS data format under the sun.

**Comment by DonLakeFlyer** [comment]
Also https://github.com/google/libkml

**Comment by Antiheavy** [comment]
Shape files are of particular importance in some industries. https://en.wikipedia.org/wiki/Shapefile

**Comment by kikislater** [comment]
Shapefile will die, gdal/ogr seems a good option IMO (there is some GIS users using Qgroundcontrol) and regarding this also it makes senses : gdal have a driver for WMS : 
http://discuss.px4.io/t/does-qgc-get-a-wms-client-any-time-soon/4788

**Comment by DonLakeFlyer** [comment]
I looked at integrating a kml reading library. Trying to get something like that to work cross-platform turned out to be a nightmare. So instead a wrote some very simple KML polygon loading code. I tested with polygon output from Google Earth and it works. But not sure if there are any quirks in other Polygon formats I may not have taken into account. So testing with any KML polygon files you have would be appreciated.

Also I'm going to try to get away with kml only support in 3.3. May look at other formats in later releases.

**Comment by DonLakeFlyer** [comment]
KML is in 3.3 release. SHP will be in 3.4

**Comment by tubeme** [comment]
One quick question. I use the 3.3.2 and don't seem to find a way to import kml... @DonLakeFlyer can you give me a pointer? thanks.

**Comment by DonLakeFlyer** [comment]
You need to use a daily build

**Comment by tubeme** [comment]
OK thanks I saw it in the Master. It translates directly in corridor survey. Is there a way to import the KML as a simple line?

What is the plan with KMZ? This is a must for the mapping guys. We met a lot of them because we tailor our craft toward the mapping. And their first question always is KLM, KMZ at least. Some ask for .shp and .poly.

**Comment by DonLakeFlyer** [comment]
> It translates directly in corridor survey. Is there a way to import the KML as a simple line?

Corridor Scan works with KML which has a line in it, not a polygon.

> What is the plan with KMZ?

None at the moment due to lack of cross platform unzip support. Users just have to unzip the KMZ themselves.

**Comment by tubeme** [comment]
Yes I tried the KML import. My question was can I import the KML not as a survey but as a straight line with  waypoints. Like a regular flight. I did not find a way to make it...

But then if we extract the KML from the KMZ manually can we generate a survey polygon if we import the KML in QGC?

**Comment by DonLakeFlyer** [comment]
> My question was can I import the KML not as a survey but as a straight line with waypoints.

Ah, nope not supported. Can you enter a separate issue with that as a feature request. Would be easy to do.

**Comment by DonLakeFlyer** [comment]
Both KML and SHP are supported now. I don't think I"m going to support .poly
