### ISSUE TITLE
QGC Menu Firmware (

### ISSUE THREAD

**Issue by taileron** [mavlink/qgroundcontrol#5861]
Firmware (QGC Mac daily and release) uploads master 1.7.0 px4fmu-v3_default.px4 instead of V2 into a PixFalcon is that a suitable FW version for that hardware as well?

**Comment by DonLakeFlyer** [comment]
@dagar I think you know more about this stuff than I do

**Comment by dagar** [comment]
@taileron yes, that's intentional. 

The build naming isn't great, but px4fmu-v3 = px4fmu-v2 + more flash and more PX4 modules. Due to a silicon bug the original pixhawk's 2MB flash had to be limited to the 1MB only. More recent pixhawks and derivatives have a later revision of the STM32F427 that resolved the issue.
