### ISSUE TITLE
Display message data bitfields as hex in MAVLink Message Inspector

### ISSUE THREAD

**Issue by Susurrus** [mavlink/qgroundcontrol#6]
Looking at the SYS_STATUS message within the Message Inspector widget it is hard to validate the values of the onboard_control_sensors_* data fields as they're shown as uint32s. Seeing '4.29496e+09' is much harder to interpret as a bitfield than the hex equivalent '0xffffe380'.

**Comment by LorenzMeier** [comment]
@Susurrus I will close this issue and a number of other issues uncommented. We have a mix of feature requests and real issue reports which is just cluttering the issue tracker. In general I recommend to not file feature requests / improvements as issue - those are things to be discussed on the mailing list.

Most of the initially worthwhile suggestions very quickly are outdated, plus we have no staff to task to implement feature requests. New features should proposed on the mailing list or straight as a pull request, simply because there is no other way to get them done.
