### ISSUE TITLE
VT_FW_MIN_ALT units do not follow preference

### ISSUE THREAD

**Issue by JonReacher** [mavlink/qgroundcontrol#6384]
VT_FW_MIN_ALT stays as meters even when using QGC with feet as the measurement unit. It also doesn't list 'ft' or 'meters' after the number entered. This can cause unexpected RTL or failure to transistion.

Real world example, I set it to 70 and tried to transition at 90 feet. It RTL'd due to min altitude breach. Changed it to 15 and it works well. I've never had another parameter not follow the measurement unit I've set in preferences.

**Comment by DonLakeFlyer** [comment]
That is because the parameter meta data (which comes from firmware) does not have units specified for this parameter. Hence QGC has no idea it is in meters.

Also FYI: If the entry field has no units shown in the ui then QGC has no idea what the units are and won't change based on setting.

Can you move this to firmware issues?
