### ISSUE TITLE
Structure scan broken on ArduPilot

### ISSUE THREAD

**Issue by lvale** [mavlink/qgroundcontrol#6824]
Hi,

While trying to upload a simple structure scan to latest ArduPilot master copter one gets this

<img width="1059" alt="screen shot 2018-08-25 at 02 52 51" src="https://user-images.githubusercontent.com/3130363/44613861-47116480-a812-11e8-80b5-2a3f37899986.png">

Using QGC master

[crash_mission.plan.txt](https://github.com/mavlink/qgroundcontrol/files/2320268/crash_mission.plan.txt)

**Comment by DonLakeFlyer** [comment]
This is because ArduPilot does not yet support the MAV_CMD_DO_SET_ROI_WPNEXT_OFFSET which is required to correctly point the vehicle or camera at the structure. I redesigned the ROI mavlink messages to support this (as well as to clean up thing that didn't work well) in coordination with PX4 and ArduPilot. PX4 implemented, ArduPilot did not. Maybe at some point it will get done. I didn't turn the feature itself off completely for ArduPilot with hopes that the user base would generate interest to get implemented.

**Comment by lvale** [comment]
Thanks @DonLakeFlyer
