### ISSUE TITLE
Scale is working erratically

### ISSUE THREAD

**Issue by Williangalvani** [mavlink/qgroundcontrol#6878]
When resizing the window vertically, the scale changes even though the map does not:
![deepin-screen-recorder_select area_20180920122155](https://user-images.githubusercontent.com/4013804/45829125-91321c80-bcd0-11e8-88a2-78979d2bc869.gif)

Tested on master in Linux and 3.4.0 in Windows

**Comment by dogmaphobic** [comment]
Interesting, this has probably been there since the beginning and no one ever caught it. I'll look into it.

**Comment by DonLakeFlyer** [comment]
Back into Stable if simple enough fix.

**Comment by dogmaphobic** [comment]
Well, it's all correct after all. The issue is that the code measures the distance between two points using where the scale is on the map. In the example above, you are moving the scale between Antartica and half way towards South Africa. The scale is showing the correct distance. It changes because of the map projection. This "error" is only seen if the change due to the projection is very large. On a "normal" use case, where your scale would be showing meters rather than thousands of kilometers, the difference due to (spherical) projection is so small to be insignificant.

**Comment by Williangalvani** [comment]
Of course! That makes perfect sense, my bad!
