### ISSUE TITLE
Calibration GUI doesn't load on Android

### ISSUE THREAD

**Issue by DavidMackie** [mavlink/qgroundcontrol#7411]
**Expected Behavior**
When calibrating I expect the full GUI to be shown on the placement of the vehicle.
![Screenshot_20190430-163619](https://user-images.githubusercontent.com/40562170/57130657-76617380-6d9a-11e9-8dd5-64865b8ca120.jpg)

**Current Behavior**
On occasions the GUI won't load and get only text feeback.
![Screenshot_20190430-163347](https://user-images.githubusercontent.com/40562170/57130679-8416f900-6d9a-11e9-8329-bb1df0d2b5ad.jpg)

**Steps to Reproduce:**
This error happens inconsistently and we haven't noticed any correlation between when the error occurs and the actions we take.
This will happen approximately once in every five attempts.

**System Information**
We are using an Android 8.1 device and connected to our drone via Bluetooth using a TBS Crossfire.
We're using;
The latest stable firmware; 1.8.2.
The latest QGC .apk for Android; 3.5.2.

**Comment by DonLakeFlyer** [comment]
This is because QGC depends on seeing the single "calibration started: ..." message which is sent from the vehicle. Without that it doesn't know if it can show visual calibration or not. On iffy telemetry this message could be lost on the way from vehicle->qgc. That is why you are only seeing this happen once in a while. You should check you mavlink loss rate in the Mavlink page. I would guess you have a noisy telemetry connection.

The fix for this is to switch to a non-text based calibration using real mavlink messages which is implemented to work over lossy telemetry. That requires both firmware and qgc changes to support. For now, there isn't anything QGC can do about this.

Writing a new protocol for this is a known thing which has been around for a really long time. But hasn't happened yet. I believe there is a firmware issue somewhere which talks about this.
