### ISSUE TITLE
Plan Wizard: suggested text for Takeoff dialog

### ISSUE THREAD

**Issue by Antiheavy** [mavlink/qgroundcontrol#7956]
After showing the [WIP] Takeoff dialog to a number of people here is some suggested improvements to the text:

Suggestions:
"Move the P near the planned launch location and move the T to the desired climbout location."
"Move P (Planned Home) near the launch location and move T (Takeoff) to the climbout location."
also
"Ensure clear of obstacles and into the wind."  (only add the "into the wind" part if you are a fixed wing)

Current:

![image](https://user-images.githubusercontent.com/12117027/67720197-4f7aa780-f9a1-11e9-99ca-b6edc7bc05dc.png)

**Comment by tilaktilak** [comment]
We can probably have a "click-to-add' instead of making it appears on the center of the map and explain to the user that he has to move it ? That will make user experience more sensible.    

Also I think the Takeoff / Planned Home behavior is different depending on MultiCopter, Plane, ArduPilot, PX4, ... I put that here.

**Comment by DonLakeFlyer** [comment]
> We can probably have a "click-to-add'

Done.

> here is some suggested improvements to the text:

I lost track of this one when I was making changes in #8049. I'll fix this up.

**Comment by DonLakeFlyer** [comment]
Wording changes are done
