### ISSUE TITLE
Display waypoint numbers as setting

### ISSUE THREAD

**Issue by sanderux** [mavlink/qgroundcontrol#8098]
With regards to the recent change https://github.com/mavlink/qgroundcontrol/pull/7779
Please allow enabling this on a setting as some systems use the numbers to refer to issues.

**Comment by DonLakeFlyer** [comment]
I changed the following in the Terrain display in Plan:
* Shows sequence numbers
* Clickable to select item
* Hide/Show state persists

So the information there can be used to understand the mission item numbering with respect to the your validation of feasability check failures. I know it's not the greatest. But I don't want to bring back numbering everywhere (even optionally) since I plan to fix this with a mavlink proposal for how to report feasability errors. Which I can then use to more directly indicate errors.
