### ISSUE TITLE
Multiple missions issue

### ISSUE THREAD

**Issue by dogmaphobic** [mavlink/qgroundcontrol#8192]
This is a bit convoluted to explain but simple to reproduce.

Start QGC and connect to multiple vehicles:
<img width="1088" alt="Screen Shot 2019-12-30 at 1 06 18 PM" src="https://user-images.githubusercontent.com/749243/71594627-9d796c00-2b06-11ea-96cb-ac32e8735d5d.png">

Select Vehicle 1, switch to the Plan View, add 2 waypoints and upload the "mission" to the vehicle:
<img width="1088" alt="Screen Shot 2019-12-30 at 1 06 51 PM" src="https://user-images.githubusercontent.com/749243/71594644-ad914b80-2b06-11ea-8f77-fcc4093659b3.png">

Back to the Fly View the mission is ready to be started and everything is fine:
<img width="1088" alt="Screen Shot 2019-12-30 at 1 07 00 PM" src="https://user-images.githubusercontent.com/749243/71594688-ea5d4280-2b06-11ea-9b2f-afff9bf19910.png">

Now select Vehicle 2:
<img width="1088" alt="Screen Shot 2019-12-30 at 1 07 06 PM" src="https://user-images.githubusercontent.com/749243/71594697-f34e1400-2b06-11ea-9286-2d6034f77d21.png">

Switch to Plan View and add a single way point. This should be the first waypoint for Vehicle 2:
<img width="1088" alt="Screen Shot 2019-12-30 at 1 07 26 PM" src="https://user-images.githubusercontent.com/749243/71595061-4379a600-2b08-11ea-9ec5-ee181f6d8606.png">

Upload that "single-waypoint-that-isn't-single" mission to Vehicle 2, switch back to Fly View and start the mission. Both vehicles are flying to the Vehicle 1's second waypoint:
<img width="1088" alt="Screen Shot 2019-12-30 at 1 09 33 PM" src="https://user-images.githubusercontent.com/749243/71595091-5e4c1a80-2b08-11ea-9e36-d1bbf72b9565.png">

Once Vehicle 1 reaches the second waypoint (its last), it stops as expected and Vehicle 2 proceeds to its "first" waypoint.
<img width="1088" alt="Screen Shot 2019-12-30 at 1 10 22 PM" src="https://user-images.githubusercontent.com/749243/71595163-8fc4e600-2b08-11ea-8ff6-73ad9324b317.png">

Is this expected? How do I get multiple vehicles to go to different places?

**Comment by DonLakeFlyer** [comment]
> Switch to Plan View and add a single way point. This should be the first waypoint for Vehicle 2:

When you upload a Plan QGC always uploads the entire Plan. Hence Vehicle 2 gets the whole Plan. Not just the last waypoint you added. And Vehicle 1 still has what it had before.

Creating plans with multiple vehicles connected is not super easy. The Plan view does not track current vehicle switches. The reason for this is that trying to do that and deal with a possibly dirty plan on the vehicle you are switching away from is a nightmare. And given the fact that multiple vehicle support is used almost never it's not a focus to make easier.

In order to send Plans to multiple vehicles you just need to understand that whatever you are seeing in the Plan view is going to be sent to the current vehicle.

**Comment by DonLakeFlyer** [comment]
> Now select Vehicle 2:

There may be a bug here. Assume Vehicle 2 at this point has no mission items on it. Is that correct? Yet a part of the Plan for Vehicle 1 is still being shown.

**Comment by dogmaphobic** [comment]
Got it. The way to solve that would be to have an instance of the mission controller on each vehicle. That way it's always in sync with that vehicle. The Plan View would then point to `activeVehicle.missionController` instead.

> There may be a bug here. Assume Vehicle 2 at this point has no mission items on it. Is that correct? Yet a part of the Plan for Vehicle 1 is still being shown.

Correct. This is a first boot for everything. Nothing had any mission previously loaded. The mission you see when vehicle 2 is selected is the one for Vehicle 1. I didn't think of it as a bug. It correctly shows an existing mission. If you were to only see the mission for the current vehicle, we would then need a way to allow multiple vehicle selection so we could see them all.

**Comment by DonLakeFlyer** [comment]
> The mission you see when vehicle 2 is selected is the one for Vehicle 1.

Ok, I remember. Originally I had only the active vehicle showing the mission. At some point I changed it. But as it currently stands it is only half-assed implemented. For example rally points and geofence only show for current vehicle. Hard to say what is correct because things will get cluttered really fast if you show everything.

**Comment by DonLakeFlyer** [comment]
> The way to solve that would be to have an instance of the mission controller on each vehicle.

Which is how Fly view works, but that's a much simpler case. That's how to make it work for Plan but just the tip of the icerberg for problems.

**Comment by DonLakeFlyer** [comment]
So anyway, as it currently stands this is working correctly.
