### ISSUE TITLE
How to enable airmap function for MacOS QGroundControl

### ISSUE THREAD

**Issue by anxueshen** [mavlink/qgroundcontrol#8767]
hi guys,
I am a beginner to QGroundControl. And I want to enable airman function in QGroundControl. And I use MacOS with QT 5.12 to compile the QGroundControl project. But in the **QGCExternalLibs.pri** file:

```
AIRMAPD_PATH    = $$PWD/libs/airmapd

AIRMAP_QT_PATH  = Qt.$${QT_MAJOR_VERSION}.$${QT_MINOR_VERSION}

MacBuild {
    exists($${AIRMAPD_PATH}/macOS/$$AIRMAP_QT_PATH) {
        message("Including support for AirMap for macOS")
        LIBS += -L$${AIRMAPD_PATH}/macOS/$$AIRMAP_QT_PATH -lairmap-qt
        DEFINES += QGC_AIRMAP_ENABLED
        }
}
```
The AIRMAP_QT_PATH = Qt.5.12, but in the source code folder, there is only Qt.5.11 version MacOS(qgroundcontrol/libs/airmapd/macOS/Qt.5.11/). Does I need to update the airmapd version, or just rename the path to Qt.5.12?

One more question, I only found Linux and Mac support for Airmap. And In Airmap official website, there is Android and iOS version SDK. And how to enable QGroundControl to support Android and iOS platform.

Best Regards,
Alan

**Comment by dogmaphobic** [comment]
I'm not sure what is the current state of the AirmapSDK. The one we use is a general use sdk, which I haven't seen anything new in quite some time. They stopped at Qt 5.11 and only had macOS fully functional. The more recent SDKs are targeting iOS and Android natively, which doesn't work for us (a Qt Application). Until I hear something different, AirMap support for QGC is all but non-existent at the moment due to the lack of an updated sdk.
