### ISSUE TITLE
detecting xbox controller when running the app in docker container

### ISSUE THREAD

**Issue by abarghou1993** [mavlink/qgroundcontrol#9041]
Tell us a bit about the feature:
- What problem does it solve? launch multiple QGroundControl applications on a single machine
- What does it do? need a docker version of QGroundControl
- What flight stacks must it work with? (All, PX4, ArduPilot) px4
- Relevant vehicle types? (All, multirotor, fixed-wing, VTOL, submarine, etc.) drone
- Are there other systems that have this feature?
- What communication/integration standards does the feature rely on (e.g. MAVLink commands etc.) mavlink commands

Any additional context you can provide will make the feature easier to evaluate (e.g. mockups, detailed specification, etc.)
i was able to run QGroundConrol from docker the only issue was detecting the joystck in the application after connecting to px4. the xbox joystick was detected in the docker container but not in the QGroundControl application

**Comment by DonLakeFlyer** [comment]
I don't see how there could be anything QGC could do differently. It has no idea whether it is running in a native OS or in a VM. If the VM is working correctly there should be no difference to a running app. 

So two possiblities:
* The joystick is not exposed correctly in the VM hence QGC doesn't see it
* For some reason the joystick is exposed in the VM but in a way in which QGC does not support. If this is the case there isn't anything QGC can do since the joystick support code is provided to QGC through an external libary. So if it is not supported by that library then it is simply not supported by QGC either.
