### ISSUE TITLE
improve documentation about ADS-B

### ISSUE THREAD

**Issue by booo** [mavlink/qgroundcontrol#9068]
Documentation about ADS-B setup is very minimal:

https://docs.qgroundcontrol.com/master/en/SettingsView/General.html#adbs_server

We should improve the documentation.

If I get some pointers in the right direction I can setup a test system and write some documentation.

**Comment by DonLakeFlyer** [comment]
@antiheavy Wondering if you guys ever wrote up any docs for this for you Sentera usage?

It's similar to this: https://discuss.ardupilot.org/t/ads-b-mission-planner-and-flightaware-ads-b-dongle/21362

Basically an SDR, and then dump1090 spitting out "sbs" format if I remember correctly. Some more details in the pull: https://github.com/mavlink/qgroundcontrol/pull/8046

**Comment by hamishwillee** [comment]
FYI, I just fixed up the spelling of that section, which was all "ADBS" not "ADSB" - when that fix propagates the docs pointed to above will move link to https://docs.qgroundcontrol.com/master/en/SettingsView/General.html#adsb_server

Yes it is minimal. I have no idea how this works. Would be great if we can get some information on how it should work so that this can be documented. Thanks @booo !

**Comment by booo** [comment]
I used https://github.com/antirez/dump1090 with the --net option. Worked fine. I saw the plane in QGC.

**Comment by booo** [comment]
I think the issues is fixed with https://github.com/mavlink/qgc-user-guide/pull/277
