### ISSUE TITLE
The relative altitude is reported in thousands of meters instead of meters : bad scaling

### ISSUE THREAD

**Issue by dorovl** [mavlink/qgroundcontrol#9415]
The relative altitude is reported in thousands of meters instead of meters : bad scaling.
This has been reproduced on the v4.1.0 and v4.1.0 on Android 32 bit and also on Windows 10.
The behaviour is OK on a v4.0.11 (regression suspected).
The flight controller used is [rosettadrone ](https://github.com/The1only/rosettadrone) which uses the Ardupilot dialect.

See below on Android:
![Screenshot_20210124-182440](https://user-images.githubusercontent.com/8594515/107125215-d60e7c00-68a8-11eb-836a-eaddbbc24740.jpg)

Same on Windows:
![2021-02-06 18_09_26-Window](https://user-images.githubusercontent.com/8594515/107125382-fc80e700-68a9-11eb-869c-adc2ba6f185f.png)

**Comment by DonLakeFlyer** [comment]
I tested using ArduPilot master SITL and it is working correctly. QGC uses the following for the relative altitude value:
* If the `ALTITUDE` message is available it uses that (https://mavlink.io/en/messages/common.html#ALTITUDE). I think this might be new in 4.1.
* Otherwise it uses the value from `GLOBAL_POSITION_INT`(https://mavlink.io/en/messages/common.html#GLOBAL_POSITION_INT)
* I also checked the code for both of those and it is doing the right thing.

My guess would be that your firmware is sending values on one of these messages in the wrong units. You should be able to verify using the mavlink inspector. I you can should that the mavlink message is sending the right data, but QGC is showing the wrong value I will reopen. In that case include a telemetry log which shows the repro.
