### ISSUE TITLE
MAV_FRAME ignored by the elevation profile

### ISSUE THREAD

**Issue by remster** [mavlink/qgroundcontrol#9480]
## Expected Behavior
The Elevation Profile should interpret the altitudes of the mission `MAV_CMD_NAV_WAYPOINT` commands according to the `MAV_FRAME` they are listed with (and thus the same way as the vehicle would interpret them).

## Current Behavior
Presumably in presence of `"FollowTerrain": true` the Elevation Profile ignores the `MAV_FRAME` and assumes the survey is flown at AMSL. 
If you load [this](https://github.com/mavlink/qgroundcontrol/files/6029298/follow-terrain-survey.zip) plan - a plan that consistently uses `frame": 3` (`MAV_FRAME_GLOBAL_RELATIVE_ALT`) for all `MAV_CMD_NAV_WAYPOINT`s you will see this after loading it QGC 4.1.1:
![under-ground](https://user-images.githubusercontent.com/8327961/108854056-b6d15780-75e7-11eb-9c90-49a0f3107d9b.png)

The survey is under ground - even though.. it isn't. 

## System Information
When posting bug reports, include the following information
- Operating System: N/A
- QGC Version: 4.1.1
- QGC build: stable
- Flight Controller: N/A
- Autopilot (with version): N/A

## Detailed Description
You may remember [me saying](https://github.com/mavlink/qgroundcontrol/pull/8682#issuecomment-619275448):
"I fear our reference drone has problems flying AMSL so i may find myself in a pickle"
And indeed, this continues to be the case. One of our reference drones simply will not fly AMSL missions - it insists all altitudes are relative to takeoff, it ignores `MAV_FRAME`, it shoots out to the sky, it does not implement MAVLINK correctly.

We learnt to cope - after we generate `.plan` with `followTerrain == true` - we translate all altitudes to relative to takeoff. Has been serving us well all this time. I think this demonstrates a genuine need and yes, i am wary of @DonLakeFlyer 's words:

> You can't follow terrain using relative altitudes based on a planned home position altitude. The position you specified when you > planned the mission not connected to the vehicle could be different from when you fly the mission

We cope with this rendering the plan just-in-time. And we really have no choice but to find a way to cope.

**Comment by DonLakeFlyer** [comment]
I believe your tweaking of the .plan after the fact is confusing QGC. I load the plan and see this:
![Screen Shot 2021-03-20 at 10 55 53 AM](https://user-images.githubusercontent.com/5876851/111880841-f3843a80-896a-11eb-9c56-0fe44cfc3f09.png)

You are half in one mode and half in another. You may be able to work around this by futzing with the survey item itself in the plan not sure. The surefire workaround is this:
* Generate the plan using follow terrain
* Round trips it trough a vehicle so it degenerates into individual waypoints
* Tweak that plan back to AMSL

I'm not sure the way you are doing it now will ever work. QGC doesn't really have full validation/verification of .plan files which are hand created. That is unlikely to be fixed any time soon since it is so rare. Hence I don't place on fixing the specific .plan load problem.
