### ISSUE TITLE
Use Airspeed Sensor on Quadcopter 

### ISSUE THREAD

**Issue by SyedShayaan** [mavlink/qgroundcontrol#9891]
Hi there, I have been looking for about 2 weeks to use an airspeed sensor with a quadcopter design.  I have learned that by default that airspeed sensors are disabled for quadcopters and are only available for fixed winged aircrafts.  I am working with a Pixhawk 4 and am using the Holybro X500 frame. I have attempted to manually enable the airspeed sensor parameters as stated 
here: https://docs.px4.io/master/en/config/airspeed.html
by enablling the following parameters:
Sensirion SDP3X (SENS_EN_SDP3X)
TE MS4525 (SENS_EN_MS4525)
TE MS5525 (SENS_EN_MS5525)
Eagle Tree airspeed sensor (SENS_EN_ETSASPD)

However I do not see these parameters in the parameters list.

Any guidance would be appreciated. 

Thanks.

**Comment by Davidsastresas** [comment]
I think this is a PX4 question rather than QGC one. You might have better luck asking in PX4 forums or chats.

For your information, QGC reads the mavlink message VFR_HUD, so if PX4 is sending that message QGC should display airspeed. You can check in mavlink inspector if you are receiving a particular mavlink message. Best regards!
